---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  parallelism: 4
  plugin_directory: terraform.d/plugins
  command_timeout: 3600

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: controls
      backend: local
      controls:
        - file_check

platforms:
  - name: terraform

suites:
  - name: kt_suite